version: "2.1"
services:
  vpn:
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=Rundle.r97@gmail.com
      - PASS=g_ReYqxaCv!3pPmi6aXmm
      - COUNTRY=United States;Canada;Gernmany
      - GROUP=Standard VPN servers
      # - RANDOM_TOP=10
      # - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.1.0/24;192.168.2.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    container_name: qbittorrent-${NAMESPACE}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={$TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${PATH_QBIT_CONF}:/config
      - ${PATH_QBIT_DOWNLOADS}:/downloads  
    restart: unless-stopped

  rclone:
    image: lucashalbert/rclone
    container_name: rclone-${NAMESPACE}
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    privileged: true
    volumes:
      - ${PATH_RCLONE_CONF}:/config
      - ${PATH_RCLONE_HOSTDIR}:/mnt:rw
    environment:
      - CONFIG=--config /config/rclone.conf
      - SUBCMD=mount
      - "PARAMS=-vv --allow-other --drive-chunk-size 4M --dir-cache-time=336h --cache-info-age=1344h --cache-chunk-size 4M --cache-chunk-total-size=50G --cache-tmp-wait-time=1h --vfs-cache-mode=writes --write-back-cache --tpslimit=8 ${RCLONE_CONNECTION} /mnt"
    # restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett-${NAMESPACE}
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - ${PATH_JACKETT_CONF}:/config 
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr-${NAMESPACE}
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${PATH_RADARR_CONF}:/config
      - ${PATH_RADARR_MOVIES}:/movies #optional
      - ${PATH_QBIT_DOWNLOADS}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr-${NAMESPACE}
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${PATH_SONARR_CONF}:/config
      - ${PATH_SONARR_TV}:/tv #optional
      - ${PATH_QBIT_DOWNLOADS}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  